### ISSUE TITLE
Docker-compose command - Build client for production

### ISSUE THREAD

**Issue by Thenkei** [Thenkei/UnderTheLimits#23]
https://github.com/Thenkei/UnderTheLimits/blob/863f28d724d0315a804402c793c73a5a1bb99060/docker-compose.yml#L28

Change to npm run build

**Comment by jeffladiray** [comment]
You can even build the app on circleci, then expose the built package as an artifact.
We can also try [this](https://github.com/gitname/react-gh-pages), that should work for the client app. Server still need to be hosted elsewhere :/

**Comment by jeffladiray** [comment]
Fixed by #40
