### ISSUE TITLE
Add simple bot to make test easier

### ISSUE THREAD

**Issue by jeffladiray** [Thenkei/UnderTheLimits#42]
We could really use a simple bot to run game on dev env

**Comment by Thenkei** [comment]
I will take a look at this improvement.
The simplest version could be a random selection on the player (AI) hand. 

@SigmundFrog will add sets/types, so we could have better match between Question and Answers cards.

**Comment by Thenkei** [comment]
This work is now a separate project named OverTheLimits.

**Comment by Thenkei** [comment]
Look at [OverTheLimits](https://github.com/Thenkei/OverTheLimits). There is the simplest BOT for test purpose.
