### ISSUE TITLE
Tchat service

### ISSUE THREAD

**Issue by Thenkei** [Thenkei/UnderTheLimits#50]
Simple tchat implementation.

Will be then used in lobby and channels.

**Comment by Thenkei** [comment]
We can use this kind of solution with a custom socket handling tchat segmentation: https://github.com/socketio/chat-example

**Comment by jeffladiray** [comment]
So just a single `chat/message` call to send a message, and a `chat/update` to update other client chat ? I can manage that one :)

**Comment by jeffladiray** [comment]
Related to #57
