### ISSUE TITLE
Customizable party

### ISSUE THREAD

**Issue by Thenkei** [Thenkei/UnderTheLimits#51]
When creating the game, the salon creator can choose several parameters:
- number of points to accumulate to win the game
- maximum number of players and spectators in the game (example: min 3, max 8)
- Play the Vanilla version or the "UTL PLUS" version
- the deck he wants to use (for "UTL PLUS" versions)
- change the method of allocation of points, indicate to the creator of the show that he must provide
a higher point limit and explain the difference (for "UTL PLUS" versions)

**Comment by jeffladiray** [comment]
Not working correctly

**Comment by Thenkei** [comment]
What is still missing ?

**Comment by jeffladiray** [comment]
I saw some flacky behaviour on dev. Moreover, client doesn't check for room params to be ok

**Comment by Thenkei** [comment]
Closed with eab98bf89b77dd957e25ab48a5d41e2265858128
