### ISSUE TITLE
Allow channel to automatically kick player if they are not playing for a couple of rounds

### ISSUE THREAD

**Issue by jeffladiray** [Thenkei/UnderTheLimits#66]
Allow admin to kick player ?

**Comment by Thenkei** [comment]
That can be a feature.

**Comment by Thenkei** [comment]
Yesterday I was playing Rocket League and I thaught about the channel class (on the server side). I think we can see it more of a group (as in RL) kind of functionalities including this one.

**Comment by Thenkei** [comment]
If player don't play for X rounds then the player is kicked.

**Comment by Thenkei** [comment]
Need UTLPlayer serializer in order to add player.numberAFKRound data member.
How to send to a player that he is being kicked ?

**Comment by Thenkei** [comment]
New player property AfkCount. We need to do a **client-side trick** to kick the not playing player...
