### ISSUE TITLE
Shifting chat messages is not working

### ISSUE THREAD

**Issue by jeffladiray** [Thenkei/UnderTheLimits#69]
I might have done something wrong here 
https://github.com/Thenkei/UnderTheLimits/blob/master/client/src/reducers/chat.js

Will check tomorrow

**Comment by Thenkei** [comment]
https://github.com/Thenkei/UnderTheLimits/blob/79fc8a86d869d18ebc1978c7193a054ef60facc0/client/src/reducers/chat.js#L58-L60

Just need to do:
`messages.shift();`

Am I right ?
